[package]
name = "euler044"
version = "0.1.0"
authors = ["Paweł Sacawa <psacawa@math.toronto.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
